### ISSUE TITLE
Rounding?

### ISSUE THREAD

**Issue by dpsanders** [JuliaArbTypes/ArbFloats.jl#11]
What is the situation with rounding? The following should give different results:
```
julia> setrounding(ArbFloat, RoundUp) do
         @ArbFloat(1.3)
       end
1.3

julia> setrounding(ArbFloat, RoundDown) do
         @ArbFloat(1.3)
       end
1.3
```

**Comment by JeffreySarnoff** [comment]
the right way to do this requires doubling the C interface to cover the types that are used to construct Arb values -- and that is only useful if more capabilities comes with it (unlikely) -- so I am putting this to bed
