### ISSUE TITLE
min with `ArbFloat(Inf)`

### ISSUE THREAD

**Issue by lbenet** [JuliaArbTypes/ArbFloats.jl#17]
I just noticed the following (odd) behavior, which is breaking some code:

```julia
julia> min(ArbFloat(-Inf), ArbFloat(0.125))  # odd notation
[+/- inf]..

julia> min(ArbFloat(Inf), ArbFloat(0.125))  # !??
nan..
```

The first case above yields seemingly the expected answer though I don't quite understand the notation `[+/- inf]`; the second one is simply counter intuitive. I would have expected the result to be `ArbFloat(0.125)`.

**Comment by JeffreySarnoff** [comment]
the odd notation in the first case comes from the C Arb library which uses ako projective infinity
the second case is probably a result of the first -- but clearly problematic ... I'lll check it out.
Thank you for the heads up.

**Comment by JeffreySarnoff** [comment]
I have a fix -- working

**Comment by JeffreySarnoff** [comment]
submitted new release -- try checkout  master

**Comment by lbenet** [comment]
Thank you very much for fixing this Jeffrey! I was playing with ArbFloats.jl and this issue was breaking the possibility of combining TaylorIntegration.jl and ArbFloats together. So consider this issue as fixed!

(Incidentally, the order in which you load TaylorSeries and ArbFloats is not important!)

**Comment by JeffreySarnoff** [comment]
great -- your catches are most helpful

**Comment by JeffreySarnoff** [comment]
!!

**Comment by JeffreySarnoff** [comment]
merged

On Sat, Jun 17, 2017 at 10:25 PM, Jeffrey Sarnoff <jeffrey.sarnoff@gmail.com
