### ISSUE TITLE
Nemo-less ArbFloat?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaArbTypes/ArbFloats.jl#29]
It would be nice to lighten the dependency by not requiring Nemo. Would this be possible?

**Comment by ScottPJones** [comment]
Besides not requiring Nemo, it would be great to make things to work with the Julia GC, and be able to have struct types.
These days, a Union type with a couple of types is not so bad, so that might be an option as well to implement something that works better with Julia.

**Comment by JeffreySarnoff** [comment]
Actually, I have been considering a rewrite that is more fully an overly on
Nemo, as Nemo has evolved to a place where I could (with relative ease)
incorporate Real, Complex and maybe polys + matrix stuff into a more
Julia-friendly interface.  There is a very high hassle factor with
interfacing to Arb's C implementation directly, no disrespect to Arb --
more a matter of design.  Yet -- I am open to discuss this.

With respect to the Julia GC and union typing -- I am uniformed.

**Comment by ChrisRackauckas** [comment]
Whatever you think is best. If it helps get you features, go for it. A lightweight BigFloats replacement for multiprecision algorithms is something which is sorely needed though, and I can't add Nemo to my deps.

**Comment by JeffreySarnoff** [comment]
Arb requires GMP or alike and FLINT and MPFR, so it is not a "lightweight"
BigFloat replacement. (Arb reaches inside GMP and uses its primitives more
effectively for functions in "the medium precision range" (< 4Kbits or
better (function specific))).  FLINT (Big Integers and Rationals) [LGPL]
also depends on GMP and MPFR.  What path to our own BigFloat makes sense?

**Comment by ChrisRackauckas** [comment]
>Arb requires GMP or alike and FLINT and MPFR, so it is not a "lightweight"
BigFloat replacement. 

Well then, continue on with the approach you're doing. It makes sense then for ArbFloats to be "the big guns" when you need all the features and super fast, but not something libraries use internally. Take care.
