### ISSUE TITLE
Integration of ArbFloats with other operations including integer operations

### ISSUE THREAD

**Issue by jverzani** [JuliaArbTypes/ArbFloats.jl#35]
Pardon if I'm using this package incorrectly, but in https://discourse.julialang.org/t/root-isolation-of-real-rooted-integer-polynomials/51421/12 I was trying to use `ArbFloats` to speed up a computation that was very slow with BigFloat. I bumped into a few issues:

```
julia> using ArbFloats, IntervalArithmetic
julia> a = -ArbFloat(4); b = ArbFloat(0)
0

julia> a,b = -ArbFloat(4), ArbFloat(0)
Error showing value of type Tuple{ArbFloat{116},ArbFloat{116}}:
ERROR: MethodError: no method matching Array{String,1}(::Int64)
```

(The show method for tuples has an issue)

```
julia> Interval(a,b)
[-4, 0]

julia> a..b
ERROR: MethodError: no method matching ArbFloat{116}(::String)

julia> a:b
ERROR: MethodError: no method matching ArbFloat{116}(::Int64)
```

(Not sure where this sits, but it would be nice to have these conversions. (`ArbFloat(::Int64)` is defined, but not with the type parameter)

The latter also shows up with:

```
julia> 1/a
ERROR: MethodError: no method matching ArbFloat{116}(::Int64)
```

Thought `one(a)/a` and `1.0/a` work, as expected.

And multiplication with intervals is an issue:

```
Interval(a, b) * a
ERROR: MethodError: *(::Interval{ArbFloat{116}}, ::ArbFloat{116}) is ambiguous
```

(I'm not sure what the appropriate place is for fixing this ambiguity)

Am I just doing something wrong, or are some additional methods needed to do what i'm trying?

**Comment by JeffreySarnoff** [comment]
You should be using [ArbNumerics](https://github.com/JeffreySarnoff/ArbNumerics.jl), simply because this is much older and not often attended (by me).
The type `ArbReal` is already an interval.  In ArbNumerics, use `a = setinterval(-1.0, 4.0)`.
Ask more questions there.

**Comment by JeffreySarnoff** [comment]
referred to ArbNumerics

**Comment by JeffreySarnoff** [comment]
to get the lower and upper bounds of a result in ArbNumerics use
`upperbound(x)` and `lowerbound(x)`

**Comment by jverzani** [comment]
Thanks @JeffreySarnoff !
