### ISSUE TITLE
Inconsistent bits/digits ratio in docs

### ISSUE THREAD

**Issue by ggggggggg** [JuliaArbTypes/ArbFloats.jl#6]
"Preferred for extending the precision of floating point computations from 64 bits [17 digits] up to 1024 bits [3000 digits]. Recommended for use where elementary or special functions are evaluated to obtain results with up to 250 digits [800 bits]."

Shouldn't bits/digits be close to `log2(10)=3.32` in each case? Maybe you inverted the bits and digits in the 1024 and 3000 case? Also it would be easier to read if the order bits-digits was consistent in each case.

**Comment by JeffreySarnoff** [comment]
Thanks (q.v.) very much -- it is fixed.
