### ISSUE TITLE
Add Plot Recipes

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaArbTypes/ArbFloats.jl#7]
I think plot recipes could get interesting for ArbFloats. Maybe @tbreloff might want to weigh in. Instead of just converting them to floats and plotting them like that, I think it would be interesting if ArbFloats used their bounds information to default to some kind of ribbon plot. For example, 

`plot(t::Vector{Float64},x::Vector{ArbFloats})`

could create a ribbon plot where at each `t[i]`, you have `lo,hi = bounds(x[i])` be the bounds of the ribbon/error bars and a line through middle for the value.

**Comment by JeffreySarnoff** [comment]
error "width" at successive precisions maybe -- although that often looks
like two horizontal line segs, one near zero the other not

**Comment by JeffreySarnoff** [comment]
Chris -- I am closing this, the plot stuff is better done (more perfect results) with ArbDecimals (wip).
